
project_id = "yvgrgystclritaigvnmh"

[functions.razorpay-payment]
verify_jwt = false

[functions.sync-dictionary]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.auth-webhook]
verify_jwt = false

[functions.send-bulk-welcome-emails]
verify_jwt = false
