
project_id = "yvgrgystclritaigvnmh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-welcome-email]
verify_jwt = false

[functions.auth-webhook]
verify_jwt = false

[functions.send-bulk-welcome-emails]
verify_jwt = false

[functions.database-cleanup]
verify_jwt = false
